-- ============================================================================
-- 012_meeting_recordings.sql — Meeting recording metadata
-- ============================================================================
-- Detailed metadata for meeting replays/segments.
--
-- Dependencies: 008_meetings.sql

create table if not exists public.meeting_recordings (
  id               uuid primary key default gen_random_uuid(),
  meeting_id       uuid not null references public.meetings(id) on delete cascade,
  recording_url    text not null check (char_length(trim(recording_url)) > 0),
  status           text not null default 'ready'
                   check (status in ('processing', 'ready', 'failed', 'expired')),
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  file_size_bytes  bigint check (file_size_bytes is null or file_size_bytes >= 0),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- FK index: meeting_id (frequent lookup for a meeting's recordings)
create index if not exists meeting_recordings_meeting_id_idx
  on public.meeting_recordings (meeting_id);

-- Enable RLS
alter table public.meeting_recordings enable row level security;

-- ============================================================================
-- Comments
-- ============================================================================

comment on table public.meeting_recordings is
  'Tracks meeting recordings and replays generated by the video provider (100ms).';
comment on column public.meeting_recordings.recording_url is
  'Url to replay the video track or segment.';
comment on column public.meeting_recordings.status is
  'State of the recording asset: processing, ready, failed, or expired/deleted.';
