-- ============================================================================
-- 016_notifications.sql — In-app notifications
-- ============================================================================
-- Stores in-app notifications generated by system events or user actions.
--
-- Dependencies: 002_companies.sql, 003_profiles.sql, 013_tasks.sql

create table if not exists public.notifications (
  id           uuid primary key default gen_random_uuid(),
  company_id   uuid not null references public.companies(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id     uuid references public.profiles(id) on delete set null,
  task_id      uuid references public.tasks(id) on delete set null,
  type         text not null
               check (type in (
                 'task_assigned', 'task_completed', 'task_rejected', 'followup_created',
                 'compliance_warning', 'compliance_restored', 'compliance_terminated',
                 'invite_accepted', 'invite_sent',
                 'meeting_scheduled', 'meeting_reminder',
                 'subscription_expiring', 'subscription_expired',
                 'system'
               )),
  title        text not null check (char_length(trim(title)) > 0),
  body         text check (body is null or char_length(trim(body)) > 0),
  read_at      timestamptz,
  created_at   timestamptz not null default now(),
  metadata     jsonb not null default '{}'::jsonb
               check (jsonb_typeof(metadata) = 'object')
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Recipient unread/read feed lookup index (dashboard feed)
create index if not exists notifications_recipient_read_created_idx
  on public.notifications (recipient_id, read_at, created_at desc);

-- Company-wide notification feed lookup
create index if not exists notifications_company_created_idx
  on public.notifications (company_id, created_at desc);

-- FK index: actor_id
create index if not exists notifications_actor_id_idx
  on public.notifications (actor_id);

-- FK index: task_id
create index if not exists notifications_task_id_idx
  on public.notifications (task_id);

-- Enable RLS
alter table public.notifications enable row level security;

-- ============================================================================
-- Comments
-- ============================================================================

comment on table public.notifications is
  'In-app notification records for platform events.';
comment on column public.notifications.type is
  'Categorized notification events: tasks, compliance, meetings, subscriptions, or system.';
comment on column public.notifications.read_at is
  'Timestamp when the recipient viewed the notification. Null means unread.';
